### ISSUE TITLE
Add to device here

### ISSUE THREAD

**Issue by zihaoz96** [qanastek/HugsVision#27] opened 2021-12-10 14:41 UTC
https://github.com/qanastek/HugsVision/blob/d93cdd15da6fc9fe7f3053ca6e6d4196ef758327/hugsvision/inference/TorchVisionClassifierInference.py#L46

**Comment by qanastek** [comment] 2021-12-10 22:29
module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

**Comment by qanastek** [comment] 2021-12-11 00:59
The issue is related to the `DataParallel` layer at the end of the initialization block for the _TorchVision_ models. Thus, we need to remove the layer to make it working on CPU devices.

Note: Will be merged in the version 0.72

Code edited:
- https://github.com/qanastek/HugsVision/blob/d93cdd15da6fc9fe7f3053ca6e6d4196ef758327/hugsvision/nnet/TorchVisionClassifierTrainer.py#L117
- https://github.com/qanastek/HugsVision/blob/d93cdd15da6fc9fe7f3053ca6e6d4196ef758327/hugsvision/nnet/TorchVisionClassifierTrainer.py#L146

Sources:
- https://discuss.pytorch.org/t/does-dataparallel-matters-in-cpu-mode/7587

**Comment by qanastek** [comment] 2021-12-11 02:03
Close with the push: 8529361

**Closed by qanastek** 2021-12-11 02:03 UTC
Labels: bug, model
